openapi: 3.0.0

info:
  version: 1.0.0
  title: Example API
  description: The API specification for the example API

paths:
  /professions:
    get:
      summary: Get all professions
      description: Returns a list containing all professions
      tags:
        - Professions
      responses:
        200:
          description: A list of professions
          content:
            application/json:            
              schema:
                $ref: "#/components/schemas/Professions"
        500:
          $ref: "#/components/responses/Standard500ErrorResponse"
    post:
      summary: Create profession
      description: Adds a new profession to the list
      tags:
        - Professions
      requestBody:        
          content:          
            application/json:
              schema:
                $ref: "#/components/schemas/Profession"
      responses:
        200:
          description: Profession successfully created
          headers:
            Location:
              description: URL of the created profession
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profession"
        500:
          $ref: "#/components/responses/Standard500ErrorResponse"
  /professions/{id}:
    parameters:
      - $ref: "#/components/parameters/id"
    get:
      summary: Get profession
      description: Returns a single profession from its id
      tags:
        - Professions     
      responses:
        200:
          description: A profession
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profession"
        404:
          $ref: "#/components/responses/ProfessionDoesNotExistResponse"
        500:
          $ref: "#/components/responses/Standard500ErrorResponse"
    delete:
      summary: Delete profession
      description: Deletes a single profession from its id
      tags:
        - Professions
      responses:
        204:
          description: Profession successfully deleted
        500:
          $ref: "#/components/responses/Standard500ErrorResponse"
    patch:
      summary: Update profession
      description: Update a single profession from its id
      tags:
        - Professions
      requestBody:        
        content:          
          application/json:
            schema:
              $ref: "#/components/schemas/Profession"
      responses:
        200:
          description: Profession successfully updated
        404:
          $ref: "#/components/responses/ProfessionDoesNotExistResponse"
        500:
          $ref: "#/components/responses/Standard500ErrorResponse"

components:
  schemas:
    Profession:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          readOnly: true
        name: 
          type: string
    Professions:
      type: array
      items:
        $ref:  "#/components/schemas/Profession"
    Error:
      properties:
        code:
          type: string
        message:
          type: string
  
  responses:
    Standard500ErrorResponse:
      description: An unexpected error occured
      schema:
        $ref: "#/components/schemas/Error"
    ProfessionDoesNotExistResponse:
      description: Profession does not exist

  parameters:
    id:  
      name: id
      in: path
      required: true
      description: The profession id
      schema:
        type: integer
